### PR TITLE
config.ru issue

### PR DESCRIPTION
**Pull request by sumskyi**
added Padrino::Assets::App for those guys who uses `padrino start`;
some fixes in README

### CODE REVIEW

**Comment by nesquena** [comment]
Probably the wrong place for this but been using this gem for a project and it's been working great. Love the extensions you've built @Cirex and I noticed you contributed around Padrino a few times too @sumskyi so thanks to the both of you :)

**Comment by Cirex** [comment]
I would definitely like to fix the bug with `padrino start`, but i'm not sure if I like the idea of creating a middleware wrapper around a Rack based application to do so. Before I merge this, or take a step in this direction I would like to take some time to evaluate the options.

Maybe we can patch `Padrino.mount` in such a way that allows all Rack based applications to be mounted, and not just Sinatra derivatives

@nesquena Cheers! I still have quite a few to extract once I have the free time.

**Comment by Cirex** [comment]
For anyone who is curious. This issue exists because `padrino start` bypasses the `config.ru` file. If you are having issues getting this plugin to work, try launching your development server with `rackup` instead for the time being.

**Comment by dcu** [comment]
you should add a note to the README so we don't waste time figuring this out. IMHO you should merge this and then try to optimize because `padrino start` is the normal way to run padrino apps on development.
I am using sumskyi's fork via :git in the meantime.

**Comment by Cirex** [comment]
@dcu 

I would prefer to properly fix this rather then use a hack to fix something that is already a hack.

**Comment by dcu** [comment]
a rack app is a hack? besides it's optional, for example, I added the following lines to boot.rb it works great on dev and test:

```
if PADRINO_ENV != 'production'
  Padrino.use Padrino::Assets::App
end
```

**Comment by Cirex** [comment]
Yes, creating a middleware wrapper around a Rack application is very hacky to me.

**Pull request closed without merging**
